### ISSUE TITLE
96Boards で動かす

### ISSUE THREAD

**Issue by naobsd** [webdino/gecko-embedded#14]
# [96Boards](http://www.96boards.org/)
- [Reference Software Platform](https://github.com/Linaro/documentation/blob/master/Reference-Platform/README.md)
- Reference Platform Build - 16.09
  - OE/Yocto (Krogoth 2.1)
-  Consumer Edition
  - [DragonBoard 410c](https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/Downloads/OpenEmbedded.md)
    - [9,800円＠チップワンストップ](http://sp.chip1stop.com/dragonboard410c/)
    - 5.5mm/2.1mm -> EIAJ#3 変換ケーブルなし
    - 電源別売り
  - [HiKey](https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Downloads/OpenEmbedded.md)
    - [14,580円＠スイッチサイエンス](https://www.switch-science.com/catalog/2569/) / [株式会社ユーリカ](http://eureka-oss.com/)
    - 5.5mm/2.1mm -> EIAJ#3 変換ケーブル付き
    - 電源別売り

DragonBoard 410c, HiKey どちらも技適マークあり。
# Status
## dragonboard-410c

|  | GPU(EGL) | Firefox 45ESR |
| --- | --- | --- |
| X11 | yes | crash |
| Wayland | (TBD) | (TBD) |
## dragonboard-410c-32

|  | GPU(EGL) | Firefox 45ESR |
| --- | --- | --- |
| X11 | yes | working |
| Wayland | yes | working |
## hikey

|  | GPU(EGL) | Firefox 45ESR |
| --- | --- | --- |
| X11 | no | crash |
| Wayland | yes | crash |
## hikey-32

|  | GPU(EGL) | Firefox 45ESR |
| --- | --- | --- |
| X11 | no | slow |
| Wayland | yes | working |
# Todo
- [x] [oe-rpb-manifest](https://github.com/naobsd/oe-rpb-manifest)
- [x] [meta-rpb](https://github.com/naobsd/meta-rpb)
- [x] #9 Node.js を試す
- [x] [DragonBoard 410c 用イメージ](https://github.com/naobsd/oe-rpb-manifest/releases/tag/20161018)
- [x] wiki を書く (howto, sample)
- [ ] #15 Firefox 45ESR が aarch64 で crash する

**Comment by dynamis** [comment]
howto 少し書き始めました https://github.com/mozilla-japan/gecko-embedded/wiki/Dragon-Board-410c
頂いた sample コードをベースにまたいろいろ追記していきます。

**Comment by dynamis** [comment]
Firefox/Gecko を動かすようにするという本題以外の Node やコマンド類の更新については #36 に分離して Issue を立てました。

**Comment by dynamis** [comment]
動かすのは完了していたし、その後も普通にビルドできていたのでこちらはクローズ。
aarch 64 問題は Gecko 68 でやっと公式対応するから多分解決するんじゃないかなと思ってる (未確認)。
